# Generated by Django 4.1.7 on 2023-04-11 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_missing', models.DateField()),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('age_at_missing', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=1)),
                ('race', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detail', models.CharField(max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='persons.person')),
            ],
        ),
    ]
